-- Run this SQL in your Supabase SQL Editor to create the bookings table.

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    cake_name VARCHAR(100) NOT NULL,
    required_date DATE NOT NULL,
    required_time TIME WITHOUT TIME ZONE NOT NULL,
    query TEXT,
    pin VARCHAR(10) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable row-level security (RLS) if you wish, or keep it simple for now.
-- For a public-facing booking system and internal dashboard:
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Policy to allow anyone to insert bookings
CREATE POLICY "Allow public insert" ON bookings 
    FOR INSERT 
    WITH CHECK (true);

-- Policy to allow read/update/delete via Service Role key used by backend.
-- The service_role key bypasses RLS automatically, so no additional policies are strictly required for the backend if it uses the service_role key.
